### PR TITLE
Pool updates

### PR DESCRIPTION
**Pull request by 4fryn**
- ascend: fix typo for gregorst
- ascend: add slamper, add puredelta
- sherwood: add bitbanksy, 4fryn, bloqspace
- builders: update sherwood affiliation for 4fryn
- builders: feature 4fryn, elevate, endro
- votemanager: adjust lists to fit 101

### CODE REVIEW

**Comment by 4fryn** [comment]
There was also a rebuild of dpos-pools-data at https://github.com/vekexasia/dpos-tools-data/commit/8edb37e8fee08c7f4a7f9e29a0d7d9c62650f750

I'm currently travelling, but it's worth to have this in a new build, too.

**Comment by xunga** [comment]
@5an1ty I believe this change is not impartial and breaks the logic of "vote for max profit", by making it not true anymore. Delegates 4Fryn, Bloqspace and Bitbanksy are not forging yet and they are not mandatory. 

This would mean to remove votes from forging delegates (regularly paying out rewards) with non paying rewards yet...

**Comment by 5an1ty** [comment]
@xunga Thanks for letting me know! The information I had was incorrect and this is fixed in:
https://github.com/lisk-builders/lisk-builders/commit/d557b10397668aad1ecee8943ca69a5842e57106

**Comment by 4fryn** [comment]
Added a different option to the wizard to make this clearer #52

**Comment by xunga** [comment]
Btw @5an1ty  nice to see that I've been un-featured from Lisk.builders without any notice... 

I'm personally pretty sad for everything that happened in this PR, did we really behaved like a community here? We are 21 lisk.builders members :/

**Comment by xunga** [comment]
@4fryn A constructive feedback for you from my side... Please try to be less sly [1] next times and writing all the changes, not just the ones that suits the best for you.

You wrote in the PR description:
`builders: feature 4fryn, elevate, endro`

My advice:
```
builders: feature 4fryn, elevate, endro
builders: removed featured carbonara, joo5ty
```

[1] Without any offence, I just didn't find any other correct word in order to express myself.

**Pull request merged**
